# Generated by Django 2.2.7 on 2020-04-29 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycontracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=300)),
                ('nmck', models.FloatField()),
                ('count_goods', models.IntegerField()),
                ('tip_contracts', models.IntegerField(choices=[(1, 'Запрос котировок'), (2, 'Аукцион'), (3, 'Закупка у единственного поставщика')])),
                ('tz', models.CharField(max_length=100000)),
                ('contracts_returns', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Контракты',
                'verbose_name_plural': 'Название контракта',
                'ordering': ['object_name', 'nmck'],
            },
        ),
        migrations.CreateModel(
            name='Revisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisor_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='contracts_returns',
        ),
        migrations.AlterField(
            model_name='departments',
            name='common_name',
            field=models.IntegerField(choices=[(1, 'Департамент информационных технологий и автоматизации'), (2, 'Финансово-экономический департамент'), (3, 'Департамент труда'), (4, 'Департамент занятости')], db_index=True, default=1),
        ),
        migrations.CreateModel(
            name='Published_contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField(auto_now=True)),
                ('status_rebuild', models.BooleanField(verbose_name=bool)),
                ('contracts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycontracts.Contracts')),
            ],
        ),
    ]
